application: pittbeerdelivery
version: v1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /tasks/.*
  script: crontasks.app
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: main.app
